<?php
require_once '../../config/database.php';

// Cek login
if (!is_logged_in()) {
    header('Location: ' . BASE_URL . 'modules/auth/login.php');
    exit;
}

// Cek role (hanya admin)
if ($_SESSION['role'] !== 'admin') {
    header('Location: ' . BASE_URL . 'index.php');
    exit;
}

// Pastikan konfigurasi sudah disimpan
if (!file_exists(__DIR__ . '/../../config/hardware_settings.json')) {
    $_SESSION['error'] = "Silakan simpan konfigurasi terlebih dahulu!";
    header('Location: index.php');
    exit;
}

// Nama file zip
$zip_filename = 'jembatan_timbangan_portable_' . date('Y-m-d_H-i-s') . '.zip';
$zip_path = __DIR__ . '/../../' . $zip_filename;

// Buat file zip
$zip = new ZipArchive();
if ($zip->open($zip_path, ZipArchive::CREATE | ZipArchive::OVERWRITE) === TRUE) {

    // Tambahkan semua file kecuali yang tidak diperlukan
    $files_to_exclude = [
        '.git',
        '__pycache__',
        'node_modules',
        '*.log',
        'temp',
        'cache',
        '.env'
    ];

    // Fungsi untuk menambahkan file ke zip
    function addFolderToZip($folder, &$zip, $exclude_list) {
        $files = scandir($folder);
        foreach ($files as $file) {
            if ($file != '.' && $file != '..') {
                $file_path = $folder . '/' . $file;

                // Skip folder/file yang di-exclude
                $skip = false;
                foreach ($exclude_list as $exclude) {
                    if (strpos($file, $exclude) !== false) {
                        $skip = true;
                        break;
                    }
                }

                if (!$skip) {
                    if (is_dir($file_path)) {
                        addFolderToZip($file_path, $zip, $exclude_list);
                    } else {
                        // Hanya tambahkan file yang diperlukan
                        $allowed_extensions = ['php', 'py', 'js', 'css', 'txt', 'json', 'bat', 'html', 'md'];
                        $file_ext = pathinfo($file_path, PATHINFO_EXTENSION);

                        if (in_array(strtolower($file_ext), $allowed_extensions)) {
                            $relative_path = str_replace(__DIR__ . '/../../', '', $file_path);
                            $zip->addFile($file_path, $relative_path);
                        }
                    }
                }
            }
        }
    }

    // Tambahkan semua file dari root
    addFolderToZip(__DIR__ . '/../../', $zip, $files_to_exclude);

    $zip->close();

    // Download file
    header('Content-Type: application/zip');
    header('Content-Disposition: attachment; filename="' . $zip_filename . '"');
    header('Content-Length: ' . filesize($zip_path));
    header('Pragma: no-cache');
    header('Expires: 0');

    readfile($zip_path);

    // Hapus file zip setelah download
    unlink($zip_path);

    // Simpan log
    $log_message = "Portable package generated by user {$_SESSION['username']} on " . date('Y-m-d H:i:s');
    file_put_contents(__DIR__ . '/../../setup.log', $log_message . "\n", FILE_APPEND);

} else {
    echo "Gagal membuat file zip!";
    exit;
}
?>